export const environment = {
  countryCode: 'FI',
  defaultLocation: [61.05871, 28.18871],
  feedbackCategoryLevels: ['group', 'description', 'service_code'] as const,
  jurisdiction: 'Lappeenranta',
  privacyPolicyUrl: 'https://kartta.lappeenranta.fi/eFeedback/fi/PrivacyPolicy',
  production: true,
  pushApiUrl: '/push',
  scheduledMessagesApiUrl: '/messages',
  radarApiKey: 'your_secret_key',
  sentryDsn: 'your_secret_key',
  serviceApiApiKey: 'your_secret_key',
  serviceApiJurisdictionId: 'citizenapp',
  serviceApiUrl: 'https://kartta.lappeenranta.fi/efeedback/api/georeport/6aika',
  observationApiUrl: '/observation',
  pocketbaseUrl: '/api',
  streetAiApiJurisdictionId: 'lappeenranta',
  streetAiApiKey: 'your_secret_key',
  streetAiApiUrl: 'https://external.streetai.net/api/v1',
  streetAiUploadUrl: 'https://opendata.streetai.net/uploads',
  termsOfUseUrl: 'https://kartta.lappeenranta.fi/eFeedback/fi/TermsOfUse',
  trackingCode: 'your_secret_key',
  vapidPublicKey: 'your_public_vapid_key'
};
