apiVersion: apps/v1
kind: Deployment
metadata:
  name: baltfloods-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baltfloods-api
  template:
    metadata:
      labels:
        app: baltfloods-api
    spec:
      volumes:
      - name: baltfloods-api-persistent-storage
        persistentVolumeClaim:
          claimName: baltfloods-api-pv-claim
      containers:
        - name: baltfloods-api
          image: 'registry.k8s.gu.se/appademin/baltfloods-api:0.4.1'
          imagePullPolicy: Always
          env:
            - name: CITYSEN_SEED_CITY
              value: 'Kristiansand'
            - name: CITYSEN_SEED_LATITUDE
              value: '58.154950'
            - name: CITYSEN_SEED_LONGITUDE
              value: '8.023647'
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          volumeMounts:
          - mountPath: /pb/pb_data
            name: baltfloods-api-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  name: baltfloods-api-service
spec:
  selector:
    app: baltfloods-api
  ports:
    - protocol: TCP
      port: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: baltfloods-api
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  host: baltfloods-api.prod.appadem.in
  to:
    kind: Service
    name: baltfloods-api-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
