apiVersion: apps/v1
kind: Deployment
metadata:
  name: baltfloods-tallinn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baltfloods-tallinn-api
  template:
    metadata:
      labels:
        app: baltfloods-tallinn-api
    spec:
      volumes:
      - name: baltfloods-tallinn-api-persistent-storage
        persistentVolumeClaim:
          claimName: baltfloods-tallinn-api-pv-claim
      containers:
        - name: baltfloods-tallinn-api
          image: 'registry.k8s.gu.se/appademin/baltfloods-api:0.4.3-tallinn'
          imagePullPolicy: Always
          env:
            - name: CITYSEN_SEED_CITY
              value: 'Tallinn'
            - name: CITYSEN_SEED_LATITUDE
              value: '59.4377385'
            - name: CITYSEN_SEED_LONGITUDE
              value: '24.7330444'
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          volumeMounts:
          - mountPath: /pb/pb_data
            name: baltfloods-tallinn-api-persistent-storage
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: baltfloods-tallinn-api-service
# spec:
#   selector:
#     app: baltfloods-tallinn-api
#   ports:
#     - protocol: TCP
#       port: 8080
# ---
# kind: Route
# apiVersion: route.openshift.io/v1
# metadata:
#   name: baltfloods-tallinn-api
#   annotations:
#     kubernetes.io/tls-acme: "true"
# spec:
#   host: baltfloods-tallinn-api.prod.appadem.in
#   to:
#     kind: Service
#     name: baltfloods-tallinn-api-service
#     weight: 100
#   port:
#     targetPort: 8080
#   tls:
#     termination: edge
#     insecureEdgeTerminationPolicy: Redirect
#   wildcardPolicy: None
